
---------------------------------------BANKACCOUNT ----------------------------------
use MM
CREATE PROCEDURE SP_BANKACCOUNT (@USER_ID   INT,
                              @BNKACT_ID INT,
                              @ACCOUNT_NUMBER INT,
                              @NAME  VARCHAR(20),
                              @BANK  VARCHAR(50),
                              @IFSC_CODE VARCHAR(10),
                              @BALANCE INT)
WITH ENCRYPTION
AS
BEGIN
     INSERT INTO BANK_ACCOUNT(USER_ID,BNKACT_ID,ACCOUNT_NUMBER, NAME,BANK,IFSC_CODE,BALANCE,CREATED_DATE,MODIFIED_DATE)
     VALUES (@USER_ID,@BNKACT_ID,@ACCOUNT_NUMBER,@NAME,@BANK,@IFSC_CODE,@BALANCE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END

 
EXEC SP_BANKACCOUNT 111,1,987876545,'KOKILA','IOB','IOBA12334',7000
EXEC SP_BANKACCOUNT 112,2,7683821,'PRIYA','SBI','SBIA12784',9000

 

 

---READ ALL---
CREATE PROCEDURE SP_BANKACCOUNT_READALL
WITH ENCRYPTION
AS
BEGIN
     SELECT * FROM BANK_ACCOUNT
END

 

EXEC SP_BANKACCOUNT_READALL

 

---READ PARTICULAR RECORD---
CREATE PROCEDURE SP_PARTICULAR_BANKACCOUNT(@USER_ID INT, @BNKACT_ID INT)
WITH ENCRYPTION
AS
BEGIN
     SELECT * FROM BANK_ACCOUNT WHERE (USER_ID = @USER_ID AND BNKACT_ID = @BNKACT_ID)
END

 

EXEC SP_PARTICULAR_BANKACCOUNT 111,1

---------------------------------WALLET-----------------------------------------


ALTER PROCEDURE SP_WALLETACCOUNT_INSERT (@USER_ID  INT, @NAME VARCHAR(50),@AMOUNT INT)
WITH ENCRYPTION
AS
BEGIN
     INSERT INTO WALLET_ACCOUNT(USER_ID,NAME,AMOUNT,CREATED_DATE,MODIFIED_DATE)
     VALUES (@USER_ID,@NAME,@AMOUNT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END

 

EXEC SP_WALLETACCOUNT_INSERT 111,"KOKILA",2500
EXEC SP_WALLETACCOUNT_INSERT 112,"PRIYA",300

 
SELECT * FROM WALLET_ACCOUNT


---- READ ALL
CREATE PROCEDURE SP_WALLETACCOUNT_READALL
WITH ENCRYPTION
AS
BEGIN
    SELECT * FROM WALLET_ACCOUNT
END
EXEC SP_WALLETACCOUNT_READALL

 

------READ PARTICULAR RECORD
CREATE PROCEDURE SP_WALLETACCOUNT_PARTCLREAD @USER_ID INT
WITH ENCRYPTION
AS
BEGIN
    SELECT * FROM WALLET_ACCOUNT WHERE USER_ID = @USER_ID
END

 

EXEC SP_WALLETACCOUNT_PARTCLREAD 112

 

----UPDATE----
CREATE PROCEDURE SP_UPDATE_WALLETACCOUNT (@USER_ID   INT,@NAME VARCHAR(50), @AMOUNT INT)
WITH ENCRYPTION
AS
BEGIN
     UPDATE WALLET_ACCOUNT SET AMOUNT = @AMOUNT, NAME = @NAME ,MODIFIED_DATE = CURRENT_TIMESTAMP WHERE USER_ID = @USER_ID
END
EXEC SP_UPDATE_WALLETACCOUNT 112,"VICKY",700

 SELECT * FROM WALLET_ACCOUNT 


---DELETE----
CREATE PROCEDURE SP_DELETE_WALLETACCOUNT @USER_ID   INT
WITH ENCRYPTION
AS
BEGIN
    DELETE FROM WALLET_ACCOUNT WHERE USER_ID = @USER_ID
END

EXEC SP_DELETE_WALLETACCOUNT 112

SELECT * FROM WALLET_ACCOUNT